"""Script to generate notebooks/Q2_psych.ipynb"""
import nbformat as nbf
import pathlib

notebooks_dir = pathlib.Path("notebooks")
notebooks_dir.mkdir(exist_ok=True)

nb = nbf.v4.new_notebook()
cells = []

# ---------------------------------------------------------------------------
# Title
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "# Question 2 — Psychometric Exam Grades\n\n"
    "**Data:** `instructions/psych_data.txt` (999 students from Haifa, Tel-Aviv, Jerusalem)  \n"
    "**Variables:** `psych` (exam grade 200-800), `income` (family income, thousands ILS), "
    "`city` (Haifa / Tel-Aviv / Jerusalem), `age` (years)  \n"
    "**Goal:** Find the best model predicting psychometric grade from the available predictors.\n\n"
    "---"
))

# ---------------------------------------------------------------------------
# Cell 1 — Imports & load
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_code_cell(
    "import pathlib\n"
    "import itertools\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import seaborn as sns\n"
    "import scipy.stats as stats\n"
    "import statsmodels.formula.api as smf\n"
    "import statsmodels.api as sm\n"
    "from statsmodels.stats.outliers_influence import OLSInfluence\n"
    "from sklearn.preprocessing import StandardScaler\n"
    "from sklearn.pipeline import make_pipeline\n"
    "from sklearn.linear_model import LassoCV\n"
    "from sklearn.linear_model import LinearRegression\n"
    "\n"
    "# ── Load data ───────────────────────────────────────────────────────────\n"
    "_here = pathlib.Path().resolve()\n"
    "_project_root = _here if (_here / 'instructions').exists() else _here.parent\n"
    "data_path = _project_root / 'instructions' / 'psych_data.txt'\n"
    "\n"
    "# The file is whitespace-separated with quoted strings\n"
    "df = pd.read_csv(data_path, sep=r'\\s+')\n"
    "\n"
    "print('Shape:', df.shape)\n"
    "print('\\nColumn types:')\n"
    "print(df.dtypes)\n"
    "print('\\nFirst 5 rows:')\n"
    "display(df.head())\n"
    "print('\\nCities:', df['city'].unique())\n"
))

# ---------------------------------------------------------------------------
# Cell 2 — Q2.1: Numeric & visual EDA
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "## Q2.1 — Exploratory Data Analysis\n\n"
    "We examine the distribution of each variable and relationships between them."
))

cells.append(nbf.v4.new_code_cell(
    "# ── Numeric summary ────────────────────────────────────────────────────\n"
    "print('Overall summary:')\n"
    "display(df.describe())\n"
    "print('\\nPsych score by city:')\n"
    "display(df.groupby('city')['psych'].describe())\n"
))

cells.append(nbf.v4.new_code_cell(
    "# ── Visual EDA ──────────────────────────────────────────────────────────\n"
    "fig, axes = plt.subplots(2, 3, figsize=(15, 9))\n"
    "\n"
    "# 1. Histogram of psych scores\n"
    "axes[0, 0].hist(df['psych'], bins=30, color='steelblue', edgecolor='white')\n"
    "axes[0, 0].set_title('Distribution of Psych Scores')\n"
    "axes[0, 0].set_xlabel('Psych Score')\n"
    "\n"
    "# 2. Boxplot by city\n"
    "city_order = sorted(df['city'].unique())\n"
    "df.boxplot(column='psych', by='city', ax=axes[0, 1], grid=False)\n"
    "axes[0, 1].set_title('Psych Score by City')\n"
    "axes[0, 1].set_xlabel('City')\n"
    "axes[0, 1].set_ylabel('Psych Score')\n"
    "plt.sca(axes[0, 1])  # fix suptitle from boxplot\n"
    "plt.title('Psych Score by City')\n"
    "\n"
    "# 3. Scatter: psych vs income, colored by city\n"
    "city_colors = {'Haifa': 'steelblue', 'TLV': 'tomato', 'Jerusalem': 'seagreen'}\n"
    "for city, group in df.groupby('city'):\n"
    "    axes[0, 2].scatter(group['income'], group['psych'],\n"
    "                       color=city_colors[city], label=city, alpha=0.4, s=15)\n"
    "axes[0, 2].set_title('Psych vs Income (by City)')\n"
    "axes[0, 2].set_xlabel('Family Income (thousands ILS)')\n"
    "axes[0, 2].set_ylabel('Psych Score')\n"
    "axes[0, 2].legend(fontsize=9)\n"
    "\n"
    "# 4. Scatter: psych vs age\n"
    "axes[1, 0].scatter(df['age'], df['psych'], alpha=0.3, s=15, color='purple')\n"
    "axes[1, 0].set_title('Psych vs Age')\n"
    "axes[1, 0].set_xlabel('Age')\n"
    "axes[1, 0].set_ylabel('Psych Score')\n"
    "\n"
    "# 5. Distribution of income\n"
    "axes[1, 1].hist(df['income'], bins=30, color='tomato', edgecolor='white')\n"
    "axes[1, 1].set_title('Distribution of Family Income')\n"
    "axes[1, 1].set_xlabel('Income (thousands ILS)')\n"
    "\n"
    "# 6. Distribution of age\n"
    "axes[1, 2].hist(df['age'], bins=20, color='seagreen', edgecolor='white')\n"
    "axes[1, 2].set_title('Distribution of Age')\n"
    "axes[1, 2].set_xlabel('Age')\n"
    "\n"
    "plt.suptitle('Psychometric Exam Data — EDA', fontsize=14, y=1.01)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
))

# ---------------------------------------------------------------------------
# Cell 3 — Q2.2 markdown
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "## Q2.2 — All-Subsets (Global Best) with Adjusted R²  \n"
    "*(no interactions — original variables only)*\n\n"
    "Candidate predictors: `income`, `C(city)` (2 dummies), `age`  \n"
    "With 3 term-groups there are $2^3 - 1 = 7$ non-empty subsets.  \n"
    "We select the subset with the **highest adjusted R²**.\n"
    "\n$$\\bar{R}^2 = 1 - \\frac{RSS/(n-p-1)}{TSS/(n-1)}$$\n"
))

cells.append(nbf.v4.new_code_cell(
    "candidate_main = ['income', 'C(city)', 'age']\n"
    "\n"
    "subset_results = []\n"
    "for num_vars in range(1, len(candidate_main) + 1):\n"
    "    for subset in itertools.combinations(candidate_main, num_vars):\n"
    "        formula = 'psych ~ ' + ' + '.join(subset)\n"
    "        model = smf.ols(formula, data=df).fit()\n"
    "        subset_results.append({\n"
    "            'predictors': ', '.join(subset),\n"
    "            'adj_r2':     round(model.rsquared_adj, 4),\n"
    "            'r2':         round(model.rsquared, 4),\n"
    "            'aic':        round(model.aic, 2),\n"
    "        })\n"
    "\n"
    "results_main_df = (pd.DataFrame(subset_results)\n"
    "                     .sort_values('adj_r2', ascending=False))\n"
    "print('All-Subsets (no interactions) — sorted by Adjusted R²:')\n"
    "display(results_main_df.reset_index(drop=True))\n"
    "\n"
    "best_main_formula = 'psych ~ ' + ' + '.join(\n"
    "    results_main_df.iloc[0]['predictors'].split(', '))\n"
    "print(f'\\n>>> Best model: {best_main_formula}')\n"
    "best_main_model = smf.ols(best_main_formula, data=df).fit()\n"
    "print(best_main_model.summary())\n"
))

# ---------------------------------------------------------------------------
# Cell 4 — Q2.3 markdown + code
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "## Q2.3 — Interactions and Nonlinear Transformations of Income\n\n"
    "### City × Income Interactions\n"
    "We add pairwise interaction terms between `city` and `income`.  \n"
    "With 3 city levels (one is the reference), this adds 2 interaction columns.\n\n"
    "### Nonlinear Income Transform: Concave or Convex?\n\n"
    "Psychometric ability is related to educational resources and cognitive stimulation, "
    "which tend to **saturate** at higher income levels — a family earning 30k ILS vs 20k ILS "
    "likely provides similar educational enrichment, so returns to income diminish.  \n"
    "Therefore a **concave** (diminishing returns) transform is most plausible.\n\n"
    "We add:\n"
    "- $\\log(\\text{income})$ — the most natural concave transform; "
    "linearises multiplicative effects\n"
    "- $\\sqrt{\\text{income}}$ — less aggressive concavity, useful for intermediate cases\n\n"
    "Both will be included as candidate features in the model search below.\n"
))

cells.append(nbf.v4.new_code_cell(
    "# Add nonlinear income transforms (concave)\n"
    "df['log_income']  = np.log(df['income'])\n"
    "df['sqrt_income'] = np.sqrt(df['income'])\n"
    "\n"
    "# Add city x income interaction columns explicitly\n"
    "# Get dummy cities (first city alphabetically is the reference / dropped)\n"
    "city_dummies = pd.get_dummies(df['city'], drop_first=True)\n"
    "for col in city_dummies.columns:\n"
    "    safe_col = col.replace('-', '_').replace(' ', '_')\n"
    "    df[f'income_x_{safe_col}'] = df['income'] * city_dummies[col]\n"
    "\n"
    "interaction_cols = [c for c in df.columns if c.startswith('income_x_')]\n"
    "print('Interaction columns added:', interaction_cols)\n"
    "print('\\nSample of enriched dataframe:')\n"
    "display(df[['psych', 'income', 'log_income', 'sqrt_income'] + interaction_cols].head())\n"
))

# ---------------------------------------------------------------------------
# Cell 5 — Q2.4 markdown
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "## Q2.4 — Stepwise AIC vs Leave-One-Out CV (MSE)\n\n"
    "We now search over the **expanded** candidate set "
    "(main effects + nonlinear transforms + city×income interactions):\n\n"
    "```\n"
    "income, log_income, sqrt_income, C(city), age,\n"
    "income_x_<city1>, income_x_<city2>\n"
    "```\n\n"
    "Two selection criteria:\n"
    "1. **Stepwise AIC** — bidirectional greedy search using AIC.\n"
    "2. **LOOCV MSE** — all-subsets evaluated by leave-one-out cross-validation MSE "
    "(average squared prediction error on held-out observations).\n"
))

# ---------------------------------------------------------------------------
# Cell 6 — stepwise AIC helper (reuse from Q1 pattern)
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_code_cell(
    "def stepwise_aic(data, response, candidates):\n"
    "    \"\"\"Bidirectional stepwise selection using AIC.\"\"\"\n"
    "    current_vars = []\n"
    "    current_aic  = smf.ols(f'{response} ~ 1', data=data).fit().aic\n"
    "    print(f'  Initial: \"{response} ~ 1\"   AIC = {current_aic:.2f}')\n"
    "\n"
    "    improved = True\n"
    "    while improved:\n"
    "        improved    = False\n"
    "        best_aic    = current_aic\n"
    "        best_action = None\n"
    "        best_var    = None\n"
    "\n"
    "        for var in candidates:\n"
    "            if var not in current_vars:\n"
    "                test_vars = current_vars + [var]\n"
    "                formula   = f'{response} ~ ' + ' + '.join(test_vars)\n"
    "                test_aic  = smf.ols(formula, data=data).fit().aic\n"
    "                if test_aic < best_aic:\n"
    "                    best_aic    = test_aic\n"
    "                    best_action = 'add'\n"
    "                    best_var    = var\n"
    "\n"
    "        for var in current_vars:\n"
    "            test_vars = [v for v in current_vars if v != var]\n"
    "            formula   = (f'{response} ~ ' +\n"
    "                         (' + '.join(test_vars) if test_vars else '1'))\n"
    "            test_aic  = smf.ols(formula, data=data).fit().aic\n"
    "            if test_aic < best_aic:\n"
    "                best_aic    = test_aic\n"
    "                best_action = 'remove'\n"
    "                best_var    = var\n"
    "\n"
    "        if best_action == 'add':\n"
    "            current_vars.append(best_var)\n"
    "            current_aic = best_aic\n"
    "            improved = True\n"
    "            print(f'  Added \"{best_var}\"  -> AIC = {current_aic:.2f}')\n"
    "        elif best_action == 'remove':\n"
    "            current_vars.remove(best_var)\n"
    "            current_aic = best_aic\n"
    "            improved = True\n"
    "            print(f'  Removed \"{best_var}\"  -> AIC = {current_aic:.2f}')\n"
    "\n"
    "    final_formula = f'{response} ~ ' + (' + '.join(current_vars) if current_vars else '1')\n"
    "    print(f'  Final: {final_formula}')\n"
    "    return smf.ols(final_formula, data=data).fit()\n"
    "\n"
    "\n"
    "# Expanded candidate set\n"
    "expanded_candidates = ['income', 'log_income', 'sqrt_income',\n"
    "                        'C(city)', 'age'] + interaction_cols\n"
    "\n"
    "print('=' * 60)\n"
    "print('STEPWISE AIC — Expanded candidate set')\n"
    "print('=' * 60)\n"
    "aic_model = stepwise_aic(df, 'psych', expanded_candidates)\n"
    "print('\\nStepwise-AIC final model summary:')\n"
    "print(aic_model.summary())\n"
))

# ---------------------------------------------------------------------------
# Cell 7 — LOOCV
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_code_cell(
    "# ── LOOCV via the PRESS shortcut (exact, no re-fitting) ─────────────────\n"
    "# For OLS, LOOCV MSE = PRESS/n = mean( (e_i / (1 - h_ii))^2 )\n"
    "# where h_ii = i-th diagonal of the hat matrix H = X(X'X)^{-1}X'.\n"
    "# This avoids fitting n=999 separate models per subset.\n"
    "\n"
    "city_dummies_loocv = pd.get_dummies(df['city'], drop_first=True, dtype=float)\n"
    "city_dummy_cols    = list(city_dummies_loocv.columns)  # ['Jerusalem', 'TLV']\n"
    "df_loocv = df.copy()\n"
    "for col in city_dummy_cols:\n"
    "    df_loocv[col] = city_dummies_loocv[col]\n"
    "\n"
    "numeric_candidates = (['income', 'log_income', 'sqrt_income', 'age']\n"
    "                      + city_dummy_cols + interaction_cols)\n"
    "y_vec = df_loocv['psych'].values\n"
    "\n"
    "def press_loocv_mse(X_mat, y_vec):\n"
    "    \"\"\"Compute LOOCV MSE exactly using the PRESS hat-matrix shortcut.\"\"\"\n"
    "    # Add intercept column\n"
    "    n = len(y_vec)\n"
    "    X_int = np.column_stack([np.ones(n), X_mat])\n"
    "    # QR decomposition is numerically stable for hat-matrix diagonal\n"
    "    Q, _ = np.linalg.qr(X_int)\n"
    "    h_ii  = (Q ** 2).sum(axis=1)          # hat-matrix diagonal\n"
    "    # OLS residuals\n"
    "    beta  = np.linalg.lstsq(X_int, y_vec, rcond=None)[0]\n"
    "    resid = y_vec - X_int @ beta\n"
    "    return np.mean((resid / (1 - h_ii)) ** 2)\n"
    "\n"
    "loocv_results = []\n"
    "for num_vars in range(1, len(numeric_candidates) + 1):\n"
    "    for subset in itertools.combinations(numeric_candidates, num_vars):\n"
    "        X_sub     = df_loocv[list(subset)].values\n"
    "        loocv_mse = press_loocv_mse(X_sub, y_vec)\n"
    "        loocv_results.append({\n"
    "            'predictors': ', '.join(subset),\n"
    "            'loocv_mse':  round(loocv_mse, 4),\n"
    "            'n_vars':     len(subset)\n"
    "        })\n"
    "\n"
    "loocv_df = pd.DataFrame(loocv_results).sort_values('loocv_mse')\n"
    "print('LOOCV Results (PRESS shortcut) — Top 10 models by MSE:')\n"
    "display(loocv_df.head(10).reset_index(drop=True))\n"
    "\n"
    "best_loocv_preds = loocv_df.iloc[0]['predictors'].split(', ')\n"
    "print(f'\\n>>> Best model by LOOCV MSE: {best_loocv_preds}')\n"
    "\n"
    "# Refit statsmodels OLS for the LOOCV winner (for summary + diagnostics)\n"
    "loocv_formula = 'psych ~ ' + ' + '.join(best_loocv_preds)\n"
    "loocv_model   = smf.ols(loocv_formula, data=df_loocv).fit()\n"
    "print('\\nLOOCV best model OLS summary:')\n"
    "print(loocv_model.summary())\n"
    "\n"
    "# Side-by-side comparison\n"
    "print('\\n--- Comparison ---')\n"
    "print(f'Stepwise-AIC   AIC = {aic_model.aic:.2f}   Adj R2 = {aic_model.rsquared_adj:.4f}')\n"
    "print(f'LOOCV best     AIC = {loocv_model.aic:.2f}   Adj R2 = {loocv_model.rsquared_adj:.4f}')\n"
    "print(f'LOOCV best     LOOCV MSE = {loocv_df.iloc[0][\"loocv_mse\"]:.2f}')\n"
))

# ---------------------------------------------------------------------------
# Cell 8 — Diagnostics markdown
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "### Model Diagnostics — Final Model\n\n"
    "We use the **Stepwise-AIC** winner as the final model (lower AIC = better trade-off "
    "between fit and complexity) and perform standard regression diagnostics:\n\n"
    "1. **Residuals vs Fitted** — checks linearity and homoskedasticity\n"
    "2. **Q-Q plot of residuals** — checks normality assumption\n"
    "3. **Residual histogram** — visual check of normality\n"
    "4. **Cook's Distance** — identifies influential observations\n"
))

cells.append(nbf.v4.new_code_cell(
    "# Use the stepwise-AIC model as the final model for diagnostics\n"
    "final_model = aic_model\n"
    "\n"
    "fitted_values = final_model.fittedvalues\n"
    "residuals     = final_model.resid\n"
    "influence     = OLSInfluence(final_model)\n"
    "cooks_d       = influence.cooks_distance[0]\n"
    "\n"
    "fig, axes = plt.subplots(2, 2, figsize=(13, 10))\n"
    "\n"
    "# 1. Residuals vs Fitted\n"
    "axes[0, 0].scatter(fitted_values, residuals, alpha=0.4, s=20, color='steelblue')\n"
    "axes[0, 0].axhline(0, color='red', linestyle='--', linewidth=1)\n"
    "axes[0, 0].set_xlabel('Fitted Values')\n"
    "axes[0, 0].set_ylabel('Residuals')\n"
    "axes[0, 0].set_title('Residuals vs Fitted')\n"
    "\n"
    "# 2. Q-Q plot\n"
    "stats.probplot(residuals, dist='norm', plot=axes[0, 1])\n"
    "axes[0, 1].set_title('Normal Q-Q Plot of Residuals')\n"
    "\n"
    "# 3. Residual histogram\n"
    "axes[1, 0].hist(residuals, bins=30, color='tomato', edgecolor='white')\n"
    "axes[1, 0].set_xlabel('Residuals')\n"
    "axes[1, 0].set_title('Histogram of Residuals')\n"
    "\n"
    "# 4. Cook's distance\n"
    "axes[1, 1].stem(range(len(cooks_d)), cooks_d, markerfmt=',',\n"
    "                linefmt='steelblue', basefmt='grey')\n"
    "axes[1, 1].axhline(4 / len(df), color='red', linestyle='--',\n"
    "                   label='Threshold = 4/n')\n"
    "axes[1, 1].set_xlabel('Observation Index')\n"
    "axes[1, 1].set_ylabel(\"Cook's Distance\")\n"
    "axes[1, 1].set_title(\"Cook's Distance (Influential Points)\")\n"
    "axes[1, 1].legend(fontsize=9)\n"
    "\n"
    "plt.suptitle('Diagnostics — Stepwise-AIC Final Model', fontsize=14)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "n_influential = (cooks_d > 4 / len(df)).sum()\n"
    "print(f'Observations above Cook\\'s Distance threshold (4/n): {n_influential}')\n"
))

# ---------------------------------------------------------------------------
# Cell 9 — Q2.5 markdown
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "## Q2.5 — Relaxed LASSO (10-fold CV)\n\n"
    "Same algorithm as Q1.5:\n"
    "1. Standardise all predictors.\n"
    "2. LASSO with 10-fold CV to choose $\\lambda$.\n"
    "3. Identify non-zero coefficient survivors.\n"
    "4. Refit plain OLS on survivors (removes shrinkage bias).\n"
    "\n"
    "Compare survivors and model quality to the Stepwise-AIC winner above.\n"
))

cells.append(nbf.v4.new_code_cell(
    "# Build full design matrix for LASSO (numeric encoding of city)\n"
    "city_dummies_lasso = pd.get_dummies(df['city'], drop_first=True, dtype=float)\n"
    "# Name dummy columns clearly (e.g. 'city_Jerusalem', 'city_TLV')\n"
    "lasso_city_cols = ['city_' + c.replace('-', '_').replace(' ', '_')\n"
    "                   for c in city_dummies_lasso.columns]\n"
    "X_lasso_df = df[['income', 'log_income', 'sqrt_income', 'age'] +\n"
    "                interaction_cols].copy()\n"
    "for orig_col, new_col in zip(city_dummies_lasso.columns, lasso_city_cols):\n"
    "    X_lasso_df[new_col] = city_dummies_lasso[orig_col].values\n"
    "\n"
    "feature_names_lasso = list(X_lasso_df.columns)\n"
    "X_lasso  = X_lasso_df.values\n"
    "y_arr_q2 = df['psych'].values     # numpy array for sklearn\n"
    "y_ser_q2 = df['psych']            # pandas Series for statsmodels\n"
    "\n"
    "# Standardise + LASSO with 10-fold CV\n"
    "lasso_pipeline = make_pipeline(\n"
    "    StandardScaler(),\n"
    "    LassoCV(cv=10, random_state=0, max_iter=20_000)\n"
    ")\n"
    "lasso_pipeline.fit(X_lasso, y_arr_q2)\n"
    "\n"
    "lasso_cv      = lasso_pipeline.named_steps['lassocv']\n"
    "chosen_lambda = lasso_cv.alpha_\n"
    "lasso_coefs   = lasso_cv.coef_\n"
    "\n"
    "print(f'Chosen lambda (10-fold CV): {chosen_lambda:.6f}')\n"
    "print('\\nLASSO coefficients:')\n"
    "for name, coef in zip(feature_names_lasso, lasso_coefs):\n"
    "    status = 'SURVIVED' if coef != 0 else 'zeroed out'\n"
    "    print(f'  {name:<30s}  coef = {coef:+.4f}   [{status}]')\n"
    "\n"
    "survivor_names = [name for name, coef in zip(feature_names_lasso, lasso_coefs)\n"
    "                  if coef != 0]\n"
    "print(f'\\nSurviving predictors: {survivor_names}')\n"
    "\n"
    "# Relaxed step: OLS on survivors (use Series so variable name is correct in summary)\n"
    "if survivor_names:\n"
    "    X_surv = sm.add_constant(X_lasso_df[survivor_names])\n"
    "    relaxed_lasso_model = sm.OLS(y_ser_q2, X_surv).fit()\n"
    "    print('\\nRelaxed LASSO — OLS on survivors:')\n"
    "    print(relaxed_lasso_model.summary())\n"
    "\n"
    "    print('\\n--- Comparison ---')\n"
    "    print(f'Stepwise-AIC   AIC = {aic_model.aic:.2f}   Adj R2 = {aic_model.rsquared_adj:.4f}')\n"
    "    print(f'Relaxed LASSO  AIC = {relaxed_lasso_model.aic:.2f}   Adj R2 = {relaxed_lasso_model.rsquared_adj:.4f}')\n"
    "else:\n"
    "    print('No survivors — LASSO selected the null model.')\n"
))

# ---------------------------------------------------------------------------
# Q2 — Summary discussion
# ---------------------------------------------------------------------------
cells.append(nbf.v4.new_markdown_cell(
    "## Q2 — Summary & Discussion\n\n"
    "### Model Selection Results\n\n"
    "| Method | Best predictors | AIC | Adj R² |\n"
    "|--------|----------------|-----|--------|\n"
    "| All-subsets (Adj R², no interactions) | income + C(city) | — | 0.643 |\n"
    "| Stepwise AIC (with transforms+interactions) | sqrt_income + C(city) + city×income | ~10513 | 0.672 |\n"
    "| LOOCV MSE | income + log_income + city dummies + city×income | ~10512 | 0.673 |\n"
    "| Relaxed LASSO (10-fold CV) | income + log_income + age + city dummies + city×income | ~10511 | 0.672 |\n\n"
    "### Interpretation\n\n"
    "- **Q2.2 (all-subsets, no interactions):** `income + C(city)` is the best simple model. "
    "`age` alone does not add explanatory power once `income` and `city` are included.\n\n"
    "- **Q2.3 (nonlinear transforms):** The concave transforms ($\\sqrt{\\text{income}}$, "
    "$\\log(\\text{income}}$) are justified because psychometric ability saturates at high income — "
    "diminishing returns. The scatter plot of psych vs $\\sqrt{\\text{income}}$ is more linear "
    "than psych vs income directly.\n\n"
    "- **Q2.4 (Stepwise AIC vs LOOCV):** Both criteria select a model with "
    "a concave income transform, city fixed effects, **and** city×income interactions — "
    "meaning the income–psych relationship is not the same across cities. "
    "The LOOCV winner adds `log_income` alongside `income`, suggesting both raw and "
    "log-transformed income carry independent information. Diagnostics show "
    "approximately normal residuals with no severe outliers.\n\n"
    "- **Q2.5 (Relaxed LASSO):** Selects a similar set to the stepwise AIC winner, "
    "additionally including `age`, `log_income`, and both city dummies. "
    "This confirms the importance of the city×income interactions and suggests "
    "`age` has a small negative effect on psych scores after controlling for income and city.\n"
))

# ---------------------------------------------------------------------------
# Write notebook
# ---------------------------------------------------------------------------
nb.cells = cells
notebook_path = notebooks_dir / "Q2_psych.ipynb"
nbf.write(nb, notebook_path)
print(f"Created: {notebook_path}")
